name: Create And Publish Chart
on:
    schedule:
        - cron: "0 0 * * 0"
    workflow_dispatch:
    push:
      branches:
        - main


jobs:
    scrapeAndGenerateChart:
        runs-on: ubuntu-latest
        steps:
            - name: Install packages
              run: |
                pip install Scrapy
                pip install -U pyopenssl cryptography
                pip install pandas
                pip install plotly
                pip install dash_bootstrap_templates
            - name: Check out repo
              uses: actions/checkout@v4
            - name: Crawl
              if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
              run: |
                cd src/crawl && scrapy crawl Losses -O ../../data/losses.json
                today=$(date +%F)
                reason=${{ github.event_name}}
                echo "{\"last_update_date\": \"${today}\", \"reason\": \"${reason}\"}" > ../../data/meta.json


            - name: Generate HTML charts
              run: |
                cd src/charts
                python TankLossAgeChart.py & python TankLossBarChart.py & python CumulativeTankLossChart.py
            - name: Push changes to repo
              run: |
                git config user.name github-actions
                git config user.email github-actions@github.com
                git add .
                git commit -m "AutoGenerated"
                git push
            
